"""Add download_count to resources table

Revision ID: 6d5b5b88983b
Revises: f7b4c3d9a1e0
Create Date: 2025-12-11 22:32:34.830863

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d5b5b88983b"
down_revision: Union[str, Sequence[str], None] = "f7b4c3d9a1e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resources",
        sa.Column(
            "download_count", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resources", "download_count")
    # ### end Alembic commands ###
